apiVersion: v1
kind: ConfigMap
metadata:
  name: sect-db-init
  namespace: example-k8s
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS sects (
      id SERIAL PRIMARY KEY,
      name VARCHAR(255) NOT NULL,
      power INTEGER CHECK (power >= 0 AND power <= 100)
    );

    INSERT INTO sects (name, power) VALUES
      ('Azure Dragon Sect', 95),
      ('Phoenix Gate Academy', 88),
      ('Shadow Moon Clan', 92),
      ('Golden Lion School', 85),
      ('Jade Lotus Sanctuary', 90);
