apiVersion: v1
kind: Service
metadata:
  name: sect-client
  namespace: example-k8s
spec:
  # type: NodePort
  selector:
    app: sect-client
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 80
      # nodePort: 30002
