apiVersion: v1
kind: Service
metadata:
  name: sect-server
  namespace: example-k8s
spec:
  type: NodePort
  selector:
    app: sect-server
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001
