version: '3.8'

services:
  sect_database:
    image: postgres:15-alpine
    environment: 
      POSTGRES_DB: sectdb
      POSTGRES_USER: sectuser
      POSTGRES_PASSWORD: sectpass
    volumes:
      - sect_pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'

volumes:
  sect_pgdata: